# _config.yml
exclude:
  - gconsole/docs/  			  # Exclude the specific failing file
  - node_modules/                         # Exclude entire directories
  - vendor/
  - .github/
  - money-insight/                 # Exclude entire directories 
  - .venv/
  - README.md                             # If you don't want the README rendered

